name: zwap_design_system
description: This is a package to build a standard design system kit for any zwap projects
version: 0.1.5
homepage: https://github.com/zwap-in/zwap_design_system

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  taastrap: ^0.1.7

  zwap_utils: ^0.0.5

  provider: ^5.0.0

  get_it: ^7.1.3

  image_picker: ^0.8.2

  fluttertoast: ^8.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  fonts:
    - family: SFUITextBold
      fonts:
        - asset: assets/fonts/SFUIText-Bold.ttf

    - family: SFUITextHeavy
      fonts:
        - asset: assets/fonts/SFUIText-Heavy.ttf

    - family: SFUITextLight
      fonts:
        - asset: assets/fonts/SFUIText-Light.ttf

    - family: SFUITextMedium
      fonts:
        - asset: assets/fonts/SFUIText-Medium.ttf

    - family: SFUITextRegular
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf

    - family: SFUITextSemiBold
      fonts:
        - asset: assets/fonts/SFUIText-Semibold.ttf

    - family: SFUITextBoldItalic
      fonts:
        - asset: assets/fonts/SFUIText-BoldItalic.ttf

    - family: SFUITextHeavyItalic
      fonts:
        - asset: assets/fonts/SFUIText-HeavyItalic.ttf

    - family: SFUITextLightItalic
      fonts:
        - asset: assets/fonts/SFUIText-LightItalic.ttf

    - family: SFUITextMediumItalic
      fonts:
        - asset: assets/fonts/SFUIText-MediumItalic.ttf

    - family: SFUITextRegularItalic
      fonts:
        - asset: assets/fonts/SFUIText-RegularItalic.ttf

    - family: SFUITextSemiBoldItalic
      fonts:
        - asset: assets/fonts/SFUIText-SemiboldItalic.ttf

  assets:
    - assets/images/brand/
    - assets/images/placeholders/

