name: zwap_design_system
description: This is a package to build a standard design system kit for any zwap projects
version: 0.1.281
homepage: https://github.com/zwap-in/zwap_design_system

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0

  get_it: ^7.1.3

  collection: ^1.15.0

  textfield_tags: ^1.4.2

  taastrap: ^0.1.28

  zwap_utils: ^0.0.16

  fluttertoast: ^8.0.8

  flutter_svg: ^0.23.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: PoppinsBold
      fonts:
          - asset: fonts/poppins/Poppins-Bold.ttf
    - family: PoppinsExtraBold
      fonts:
          - asset: fonts/poppins/Poppins-ExtraBold.ttf
    - family: PoppinsMedium
      fonts:
          - asset: fonts/poppins/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
          - asset: fonts/poppins/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
          - asset: fonts/poppins/Poppins-SemiBold.ttf
    - family: ZwapIcons
      fonts:
        - asset: fonts/icons/zwap.ttf

  uses-material-design: true

  assets:
    - assets/images/brand/
    - assets/images/placeholders/
    - assets/images/icons/

