name: zwap_design_system
description: This is a package to build a standard design system kit for any zwap projects
version: 0.1.503
homepage: https://github.com/zwap-in/zwap_design_system

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.9.1"

dependencies:

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^5.0.0

  get_it: ^7.1.3

  collection: ^1.15.0

  oktoast: ^3.1.3+1

  google_fonts: ^2.1.0

  flutter_svg: ^0.23.0+1

  taastrap: ^0.1.29

  zwap_utils: ^0.0.47

  linked_scroll_controller: ^0.2.0

  shared_preferences: ^2.0.8

  url_launcher: ^6.0.20


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/brand/
    - assets/images/placeholders/
    - assets/images/icons/


  fonts:
    - family: SFUIText
      fonts:
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Light.ttf
          weight: 300
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Regular.ttf
          weight: 400
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Medium.ttf
          weight: 500
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Semibold.ttf
          weight: 600
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Bold.ttf
          weight: 700
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Heavy.ttf
          weight: 800
        - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-HeavyItalic.ttf
          weight: 800
          style: italic
