name: zwap_design_system
description: This is a package to build a standard design system kit for any zwap projects
version: 0.1.795
homepage: https://github.com/zwap-in/zwap_design_system

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.0

  get_it: ^7.1.3

  collection: ^1.15.0

  oktoast: ^3.1.3+12

  flutter_svg: ^2.0.6

  taastrap: ^0.1.29

  zwap_utils: ^0.0.47

  linked_scroll_controller: ^0.2.0

  shared_preferences: ^2.0.8

  font_awesome_flutter: ^9.1.0

  url_launcher: ^6.0.20

  percent_indicator: ^4.0.0

  intl: ^0.18.0

  flutter_sticky_header: ^0.6.5

  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/brand/
    - assets/images/placeholders/
    - assets/images/icons/

  # fonts:
  #   - family: SFUIText
  #     fonts:
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Light-subset.ttf
  #         weight: 300
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-LightItalic-subset.ttf
  #         weight: 300
  #         style: italic
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Regular-subset.ttf
  #         weight: 400
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-RegularItalic-subset.ttf
  #         weight: 400
  #         style: italic
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Medium-subset.ttf
  #         weight: 500
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-MediumItalic-subset.ttf
  #         weight: 500
  #         style: italic
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Semibold-subset.ttf
  #         weight: 600
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-SemiboldItalic-subset.ttf
  #         weight: 600
  #         style: italic
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Bold-subset.ttf
  #         weight: 700
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-BoldItalic-subset.ttf
  #         weight: 700
  #         style: italic
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-Heavy-subset.ttf
  #         weight: 800
  #       - asset: packages/zwap_design_system/fonts/SFUIText/SFUIText-HeavyItalic-subset.ttf
  #         weight: 800
  #         style: italic
